//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class partners_products
    {
        public int id_p_prod { get; set; }
        public Nullable<int> id_prod { get; set; }
        public Nullable<int> id_p { get; set; }
        public Nullable<int> count_prod { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
    
        public virtual partners partners { get; set; }
        public virtual products products { get; set; }
    }
}
