//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.AppData
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;

    public partial class partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partners()
        {
            this.partners_products = new HashSet<partners_products>();
        }
    
        public int id_p { get; set; }
        public string p_name { get; set; }
        public Nullable<int> id_pat { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<decimal> INN { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual partner_types partner_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partners_products> partners_products { get; set; }


        public string AddType
        {
            get
            {
                var type = AppConnect.model0db.partner_types.FirstOrDefault(t => t.id_pat == id_pat);

                if(type != null)
                {
                    return type.pat_name;
                }
                else
                {
                    return "Тип не указан";
                }
            }
        }

        public string AddCount
        {
            get
            {
                var count = AppConnect.model0db.partners_products.FirstOrDefault(c => c.id_p == id_p);
                if (count != null)
                {
                    return $"{count.count_prod.ToString()} продаж за год";
                }
                else
                {
                    return "Нет информации о реализации продукции";
                }
            }
        }
    }
}
