//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.partners_products = new HashSet<partners_products>();
        }
    
        public int id_prod { get; set; }
        public Nullable<int> id_pt { get; set; }
        public Nullable<int> id_mt { get; set; }
        public string prod_name { get; set; }
        public Nullable<decimal> article { get; set; }
        public Nullable<decimal> min_cost { get; set; }
    
        public virtual materila_types materila_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partners_products> partners_products { get; set; }
        public virtual product_type product_type { get; set; }
    }
}
