//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id_u { get; set; }
        public Nullable<int> id_ur { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual user_roles user_roles { get; set; }
    }
}
